### PR TITLE
Upgrade the crate for Rust 2018

### PR DESCRIPTION
**Pull request by Atul9**
Run `cargo fix --edition` to upgrade the crate for Rust 2018

### CODE REVIEW

**Comment by tobz** [comment]
Weird: it looks like `cargo fix --edition` doesn't actually fully take care of things?

https://travis-ci.org/nuclearfurnace/synchrotron/jobs/508536126#L694

A lot of this in the CI runs:

    error: unused extern crate
      --> src/main.rs:43:1
       |
    43 | extern crate slab;
       | ^^^^^^^^^^^^^^^^^^ help: remove it

**Comment by Atul9** [comment]
Yes, it's weird. I will remove the unused crates mentioned in https://travis-ci.org/nuclearfurnace/synchrotron/jobs/508536126#L694 and update the PR.

**Comment by Atul9** [comment]
@tobz I have updated the PR, please check.

**Review by tobz — APPROVED** [review]
LGTM!

**Comment by tobz** [comment]
Thanks for helping out. :D

**Pull request merged**
